{% set name = "quippy" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libAtoms/QUIP/archive/public.tar.gz
  sha256: fcebcba71f6d73ca0dfa14353fb11949cf0b0aa2daf0563baf7dc7708d1b4eb6
  patches:
    - options.patch  # configure quip by patching the makefile rather than using the interactive configuration 
    - fox.patch  # use the fox package from conda-forge
    - quippy.patch  # use the f90wrap package from conda-forge 

build:
  number: 4
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - libgomp  # [linux]
  host:
    - python
    - setuptools
    - ase
    - numpy
    - f90wrap >=0.2.3
    - libblas
    - liblapack
    - fox =4.1.2=*_2
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ase
    - f90wrap >=0.2.3

test:
  imports:
    - quippy

about:
  home: https://libatoms.github.io
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'libAtoms/QUIP molecular dynamics framework'

  description: |
    The QUIP package is a collection of software tools to carry out 
    molecular dynamics simulations. It implements a variety of 
    interatomic potentials and tight binding quantum mechanics, and is 
    also able to call external packages, and serve as plugins to other 
    software such as LAMMPS, CP2K and also the python framework ASE. 
    Various hybrid combinations are also supported in the style of QM/MM, 
    with a particular focus on materials systems such as metals and 
    semiconductors.
  doc_url: https://libatoms.github.io
  dev_url: https://github.com/libAtoms/QUIP

extra:
  recipe-maintainers:
    - jan-janssen
